// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMiEFAcGysWe7_InVGq1UisTMmhM7l2c',
    appId: '1:330501476875:web:6a08066663887ef1892d0e',
    messagingSenderId: '330501476875',
    projectId: 'poultrypro-8a77c',
    authDomain: 'poultrypro-8a77c.firebaseapp.com',
    storageBucket: 'poultrypro-8a77c.firebasestorage.app',
    measurementId: 'G-FXQWPYKE7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7uaDzjtZqbhhw46MN6iRspJz4M8rzKgg',
    appId: '1:330501476875:android:6f526dc99ff61bfc892d0e',
    messagingSenderId: '330501476875',
    projectId: 'poultrypro-8a77c',
    storageBucket: 'poultrypro-8a77c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDj4sMzjMBeRZMFhjdjQ7XiUy0en7z-c',
    appId: '1:330501476875:ios:5ac80cb7fd655509892d0e',
    messagingSenderId: '330501476875',
    projectId: 'poultrypro-8a77c',
    storageBucket: 'poultrypro-8a77c.firebasestorage.app',
    iosClientId: '330501476875-jep2qpkdnp545spdo1ksmi487d83valp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDj4sMzjMBeRZMFhjdjQ7XiUy0en7z-c',
    appId: '1:330501476875:ios:5ac80cb7fd655509892d0e',
    messagingSenderId: '330501476875',
    projectId: 'poultrypro-8a77c',
    storageBucket: 'poultrypro-8a77c.firebasestorage.app',
    iosClientId: '330501476875-jep2qpkdnp545spdo1ksmi487d83valp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoMiEFAcGysWe7_InVGq1UisTMmhM7l2c',
    appId: '1:330501476875:web:c69e09096f9232e2892d0e',
    messagingSenderId: '330501476875',
    projectId: 'poultrypro-8a77c',
    authDomain: 'poultrypro-8a77c.firebaseapp.com',
    storageBucket: 'poultrypro-8a77c.firebasestorage.app',
    measurementId: 'G-GMG4SK0S06',
  );
}
