import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

// --- FIREBASE IMPORTS ---
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire configure

// --- SECURITY & STORAGE IMPORTS ---
import 'package:local_auth/local_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';

// --- APP IMPORTS ---
import 'providers/farm_provider.dart';
import 'services/notification_service.dart';
import 'widgets/bottom_nav.dart';
import 'feature/splash_screen/splash_screen.dart'; 
import 'screens/dashboard_screen.dart';
import 'screens/feed_tracking_screen.dart';
import 'screens/egg_production_screen.dart';
import 'screens/vaccination_screen.dart';
import 'screens/profit_loss_screen.dart';

void main() async {
  // 1. Ensure Flutter bindings are initialized before calling native code (like Firebase)
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Initialize Firebase with the correct platform options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Initialize the notification service & timezones
  await NotificationService.initialize();

  // 4. Boot the app wrapped in the state management provider
  runApp(
    ChangeNotifierProvider(
      create: (context) => FarmProvider(),
      child: const PoultryProApp(),
    ),
  );
}

// ------------------------------------------------------------------------
// THE ROOT APP
// ------------------------------------------------------------------------
class PoultryProApp extends StatelessWidget {
  const PoultryProApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Poultry Pro',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF7a9a00), // Main brand green
        useMaterial3: true,
        scaffoldBackgroundColor: const Color(0xFFF4F0AA),
      ),
      // Boot the app directly into the Splash Screen
      home: const SplashScreen(), 
    );
  }
}

// ------------------------------------------------------------------------
// THE NAVIGATION SHELL & BIOMETRIC GATEKEEPER
// ------------------------------------------------------------------------
class MainNavigationShell extends StatefulWidget {
  const MainNavigationShell({super.key});

  @override
  State<MainNavigationShell> createState() => _MainNavigationShellState();
}

class _MainNavigationShellState extends State<MainNavigationShell> {
  int _currentIndex = 0;
  
  // --- BIOMETRIC STATE VARS ---
  bool _isAuthenticated = false;
  bool _isChecking = true;

  // The 5 core screens of your app
  final List<Widget> _screens = [
    const DashboardScreen(),
    const FeedTrackingScreen(),
    const EggProductionScreen(),
    const VaccinationScreen(),
    const ProfitLossScreen(),
  ];

  @override
  void initState() {
    super.initState();
    _checkBiometrics(); // Fire the security check instantly when navigating here
  }

  // --- THE GATEKEEPER LOGIC ---
  Future<void> _checkBiometrics() async {
    final prefs = await SharedPreferences.getInstance();
    final isBiometricEnabled = prefs.getBool('biometric_login') ?? false;

    // If the user turned off biometrics in Settings, let them right in
    if (!isBiometricEnabled) {
      if (mounted) {
        setState(() {
          _isAuthenticated = true;
          _isChecking = false;
        });
      }
      return;
    }

    // Renamed to 'localAuthScanner' to completely avoid 'auth' naming conflicts
    final LocalAuthentication localAuthScanner = LocalAuthentication();
    try {
      final didAuthenticate = await localAuthScanner.authenticate(
        localizedReason: 'Scan fingerprint to unlock PoultryPro',
        biometricOnly: false, // Allows PIN fallback if sensor is dirty
      );
      if (mounted) {
        setState(() {
          _isAuthenticated = didAuthenticate;
          _isChecking = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isAuthenticated = false;
          _isChecking = false;
        });
      }
    }
  }

  void _onTabSelected(int index) {
    setState(() {
      _currentIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    // 1. Show a loader while reading the biometric settings
    if (_isChecking) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator(color: Color(0xFF7A9A00))),
      );
    }

    // 2. Show the Secure Lock Screen if authentication failed or was cancelled
    if (!_isAuthenticated) {
      return Scaffold(
        body: Container(
          width: double.infinity,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: [Color(0xFFf4f0aa), Color(0xFFe8f5c0), Color(0xFFd4ebb8)],
            ),
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.fingerprint, size: 90, color: Color(0xFF7A9A00)),
              const SizedBox(height: 24),
              const Text('App Locked', style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Color(0xFF2A2000))),
              const SizedBox(height: 8),
              const Text('Biometric authentication is required', style: TextStyle(color: Colors.black54)),
              const SizedBox(height: 40),
              ElevatedButton.icon(
                icon: const Icon(Icons.lock_open, color: Colors.white),
                label: const Text('Unlock PoultryPro', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF7A9A00),
                  padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                  elevation: 8,
                  shadowColor: const Color(0xFF7A9A00).withValues(alpha: 0.5),
                ),
                onPressed: _checkBiometrics,
              ),
            ],
          ),
        ),
      );
    }

    // 3. Let them into the standard App if everything passed!
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Color(0xFFf4f0aa),
              Color(0xFFe8f5c0),
              Color(0xFFd4ebb8),
            ],
          ),
        ),
        child: SafeArea(
          // IndexedStack is the secret weapon here. It loads all 5 screens into memory 
          // but only displays the one matching the _currentIndex. This preserves state!
          child: IndexedStack(
            index: _currentIndex,
            children: _screens,
          ),
        ),
      ),
      bottomNavigationBar: CustomBottomNav(
        currentIndex: _currentIndex,
        onTap: _onTabSelected,
      ),
    );
  }
}